#!/bin/bash

warn() {
  printf "[\033[00;33mWARN\033[0m] $1\n"
}

TARGET=$1
BRANCH=$2

git add .
git commit -m "update"
git push origin $2

ssh $TARGET "sudo -u isucon /home/isucon/isuumo/deploy $BRANCH"

